# Anatol-X Calamares Ayarları
modules-search: [ local ]
instances:
- id:       netinstall
  module:   netinstall
  config:   netinstall.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - netinstall
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - luksbootkeyfile
  - luksopenswaphookcfg
  - initcpiocfg
  - initcpio
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - packages
  - bootloader
  - umount
- show:
  - finished

branding: anatolx
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false
