name: Anatol-X CI Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      - name: Runner Disk Alanı Aç
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Live-Build ve Bağımlılıkları Kur
        run: sudo apt-get update && sudo apt-get install -y live-build debootstrap curl dos2unix

      - name: Dosya Formatlarını ve İzinlerini Düzelt
        run: |
          # 1. Kopyala/Yapıştır sırasındaki gizli karakterleri ve satır sonlarını temizle
          find auto/ -type f -exec sudo dos2unix {} +
          if [ -d "config/hooks/" ]; then find config/hooks/ -type f -exec sudo dos2unix {} +; fi
          
          # 2. GitHub Web'den eklenen dosyalara çalışma (Execute) izni ver
          sudo chmod +x auto/*
          if [ -d "config/hooks/live/" ]; then sudo chmod +x config/hooks/live/*; fi

      - name: Build Ortamını Sıfırla
        run: sudo lb clean --purge

      - name: Live-Build Konfigürasyonu
        run: sudo lb config

      - name: Anatol-X ISO Build Et
        run: sudo lb build

      - name: Artifact Yükle
        uses: actions/upload-artifact@v4
        with:
          name: Anatol-X-26.0.iso
          path: ./*.iso
          retention-days: 7
